// User Endpoints
###
POST http://localhost:8000/users/register
content-type: application/json

{
    "name": "Vivek Joshi",
    "age": 27,
    "emailId": "vivek.joshi7@sjsu.edu",
    "password": "password123",
    "university": "San Jose State University",
    "program": "MSSE"
}


###
GET http://localhost:8000/users/find/vivek.joshi2@sjsu.edu
# content-type: application/json

# {
   
#     "emailId": "vivek.joshi2@sjsu.edu"
# }


###
POST  http://localhost:8000/users/login
content-type: application/json

{
   
    "emailId": "vivek.joshi22@sjsu.edu",
    "password": "password123"
}


// For Bloom-filter, we can use out the library - https://www.npmjs.com/package/bloom-filters
// or we can implement our version too


// Scholarship Endpoints


###
// How to get details of a single scholarship based on its object it
GET http://localhost:8000/scholarships/636d8a289deb4e0c598fa536


###
// Paginated API to get all the scholarships
GET http://localhost:8000/scholarships?page=1&limit=6

# {
#   "results": [
#     {
#       "_id": "636874d85ab53fa2a6c7aa7c",
#       "name": "The Aga Khan Foundation International Scholarship",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University",
#       "program": "MSSE",
#       "__v": 0
#     },
#     {
#       "_id": "636875515ab53fa2a6c7aa83",
#       "name": "Scholarship2",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University",
#       "program": "MSSE",
#       "__v": 0
#     }
#   ]
# }



###
// Paginated API to get scholarships based on a university name
GET http://localhost:8000/scholarships?university=Santa Clara University&page=1&limit=4


# {
#   "results": [
#     {
#       "_id": "63687b2ff2084f69402d6521",
#       "name": "Scholarship2",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University2",
#       "program": "MSSE",
#       "__v": 0
#     },
#     {
#       "_id": "63687b60f2084f69402d6528",
#       "name": "Scholarship2",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University2",
#       "program": "MSCE",
#       "__v": 0
#     }
#   ]
# }



###
// Paginated API to get scholarships based on a program name
GET http://localhost:8000/scholarships?program=MSSE&page=1&limit=10


# {
#   "results": [
#     {
#       "_id": "636874d85ab53fa2a6c7aa7c",
#       "name": "The Aga Khan Foundation International Scholarship",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University",
#       "program": "MSSE",
#       "__v": 0
#     },
#     {
#       "_id": "636875515ab53fa2a6c7aa83",
#       "name": "Scholarship2",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University",
#       "program": "MSSE",
#       "__v": 0
#     }
#   ]
# }



###
// Paginated API to get scholarships based on a program name and university name

GET http://localhost:8000/scholarships?university=Santa Clara University&program=MSSE&page=1&limit=4

# {
#   "results": [
#     {
#       "_id": "63687b2ff2084f69402d6521",
#       "name": "Scholarship2",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "San Jose State University2",
#       "program": "MSSE",
#       "__v": 0
#     }
#   ]
# }



###
// Paginated API to get scholarships based on user input, search is done on name and description of the scholarship using text index

GET http://localhost:8000/scholarships/search?search=Santa Clara&page=1&limit=5

# {
#   "results": [
#     {
#       "_id": "636d86ac5798ebcab4848637",
#       "name": "Santa Clara Bright Scholarship",
#       "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan.",
#       "university": "Santa Clara University",
#       "program": "MSSE",
#       "scholarshipAmount": 10000,
#       "__v": 0
#     }
#   ]
# }


###
// API to register a Scholarship
POST http://localhost:8000/scholarships/register
content-type: application/json

{
    "name": "California State University Long Beach",
    "description": "Provides scholarships to students from select developing countries who have no other source of financial help for their graduate studies. The scholarships are 50 percent grant and 50 percent loan. Eligible for Santa Clara University students too.",
    "university": "Santa Clara University",
    "program": "MSSE",
    "scholarshipAmount": 16000
}




// Application Endpoints


###
// How to apply for a scholarship
Post http://localhost:8000/scholarships/apply
content-type: application/json

{
    "userId" : "6375838f077ca5b4c2ba2e9c",
    "scholarshipId" : "636d86ac5798ebcab4848637"
}

###
// Get all the scholarship application data for a user

GET http://localhost:8000/scholarships/apply/6375838f077ca5b4c2ba2e9c?page=1&limit=5




# Indexes on MongoDB

# 1 - Text index on name and desription field of scholarships collection using query -
#     db.scholarships.createIndex({name: "text", description: "text"})

# 2 - Compound index on university and scholarshipAmount field using query -
#     db.scholarships.createIndex({"university": 1, "scholarshipAmount": 1})

# Can see the indexes created using query - db.scholarships.getIndexes()

# [
#   { v: 2, key: { _id: 1 }, name: '_id_' },
#   {
#     v: 2,
#     key: { _fts: 'text', _ftsx: 1 },
#     name: 'name_text_description_text',
#     weights: { description: 1, name: 1 },
#     default_language: 'english',
#     language_override: 'language',
#     textIndexVersion: 3
#   },
#   {
#     v: 2,
#     key: { university: 1, scholarshipAmount: 1 },
#     name: 'university_1_scholarshipAmount_1'
#   }
# ]

# # Can connect to mongoDB from terminal using -
# mongosh mongodb+srv://cmpe297:cmpe297@project.bios0vn.mongodb.net/miniworld