// User Endpoints
###
POST http://localhost:8000/user/register
content-type: application/json

{
    "firstName": "Vivek2",
    "lastName": "Joshi2",
    "age": 27,
    "emailId": "vivek.joshi222@sjsu.edu",
    "password": "password123",
    "university": "San Jose State University",
    "program": "MSSE"
}


###
GET http://localhost:8000/user/find/vivek.joshi2@sjsu.edu
# content-type: application/json

# {
   
#     "emailId": "vivek.joshi2@sjsu.edu"
# }


###
POST  http://localhost:8000/user/login
content-type: application/json

{
   
    "emailId": "vivek.joshi222@sjsu.edu",
    "password": "password123"
}


// For Bloom-filter, we can use out the library - https://www.npmjs.com/package/bloom-filters
// or we can implement our version too